// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Response.proto

package org.djr.retrofit2ee.protobuf;

public final class ResponseProtos {
  private ResponseProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:retrofit2ee.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string ip = 1;</code>
     */
    boolean hasIp();
    /**
     * <code>optional string ip = 1;</code>
     */
    java.lang.String getIp();
    /**
     * <code>optional string ip = 1;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>optional string countryCode = 2;</code>
     */
    boolean hasCountryCode();
    /**
     * <code>optional string countryCode = 2;</code>
     */
    java.lang.String getCountryCode();
    /**
     * <code>optional string countryCode = 2;</code>
     */
    com.google.protobuf.ByteString
        getCountryCodeBytes();

    /**
     * <code>optional string countryName = 3;</code>
     */
    boolean hasCountryName();
    /**
     * <code>optional string countryName = 3;</code>
     */
    java.lang.String getCountryName();
    /**
     * <code>optional string countryName = 3;</code>
     */
    com.google.protobuf.ByteString
        getCountryNameBytes();

    /**
     * <code>optional string regionCode = 4;</code>
     */
    boolean hasRegionCode();
    /**
     * <code>optional string regionCode = 4;</code>
     */
    java.lang.String getRegionCode();
    /**
     * <code>optional string regionCode = 4;</code>
     */
    com.google.protobuf.ByteString
        getRegionCodeBytes();

    /**
     * <code>optional string regionName = 5;</code>
     */
    boolean hasRegionName();
    /**
     * <code>optional string regionName = 5;</code>
     */
    java.lang.String getRegionName();
    /**
     * <code>optional string regionName = 5;</code>
     */
    com.google.protobuf.ByteString
        getRegionNameBytes();

    /**
     * <code>optional string city = 6;</code>
     */
    boolean hasCity();
    /**
     * <code>optional string city = 6;</code>
     */
    java.lang.String getCity();
    /**
     * <code>optional string city = 6;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>optional string zipCode = 7;</code>
     */
    boolean hasZipCode();
    /**
     * <code>optional string zipCode = 7;</code>
     */
    java.lang.String getZipCode();
    /**
     * <code>optional string zipCode = 7;</code>
     */
    com.google.protobuf.ByteString
        getZipCodeBytes();

    /**
     * <code>optional string timeZone = 8;</code>
     */
    boolean hasTimeZone();
    /**
     * <code>optional string timeZone = 8;</code>
     */
    java.lang.String getTimeZone();
    /**
     * <code>optional string timeZone = 8;</code>
     */
    com.google.protobuf.ByteString
        getTimeZoneBytes();

    /**
     * <code>optional string latitude = 9;</code>
     */
    boolean hasLatitude();
    /**
     * <code>optional string latitude = 9;</code>
     */
    java.lang.String getLatitude();
    /**
     * <code>optional string latitude = 9;</code>
     */
    com.google.protobuf.ByteString
        getLatitudeBytes();

    /**
     * <code>optional string longitude = 10;</code>
     */
    boolean hasLongitude();
    /**
     * <code>optional string longitude = 10;</code>
     */
    java.lang.String getLongitude();
    /**
     * <code>optional string longitude = 10;</code>
     */
    com.google.protobuf.ByteString
        getLongitudeBytes();

    /**
     * <code>optional string metroCode = 11;</code>
     */
    boolean hasMetroCode();
    /**
     * <code>optional string metroCode = 11;</code>
     */
    java.lang.String getMetroCode();
    /**
     * <code>optional string metroCode = 11;</code>
     */
    com.google.protobuf.ByteString
        getMetroCodeBytes();
  }
  /**
   * Protobuf type {@code retrofit2ee.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:retrofit2ee.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      ip_ = "";
      countryCode_ = "";
      countryName_ = "";
      regionCode_ = "";
      regionName_ = "";
      city_ = "";
      zipCode_ = "";
      timeZone_ = "";
      latitude_ = "";
      longitude_ = "";
      metroCode_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              ip_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              countryCode_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              countryName_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              regionCode_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              regionName_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              city_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              zipCode_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              timeZone_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              latitude_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              longitude_ = bs;
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              metroCode_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ResponseProtos.internal_static_retrofit2ee_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ResponseProtos.internal_static_retrofit2ee_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResponseProtos.Response.class, ResponseProtos.Response.Builder.class);
    }

    private int bitField0_;
    public static final int IP_FIELD_NUMBER = 1;
    private volatile java.lang.Object ip_;
    /**
     * <code>optional string ip = 1;</code>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string ip = 1;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ip = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRYCODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object countryCode_;
    /**
     * <code>optional string countryCode = 2;</code>
     */
    public boolean hasCountryCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string countryCode = 2;</code>
     */
    public java.lang.String getCountryCode() {
      java.lang.Object ref = countryCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          countryCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string countryCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCountryCodeBytes() {
      java.lang.Object ref = countryCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        countryCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRYNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object countryName_;
    /**
     * <code>optional string countryName = 3;</code>
     */
    public boolean hasCountryName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string countryName = 3;</code>
     */
    public java.lang.String getCountryName() {
      java.lang.Object ref = countryName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          countryName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string countryName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCountryNameBytes() {
      java.lang.Object ref = countryName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        countryName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REGIONCODE_FIELD_NUMBER = 4;
    private volatile java.lang.Object regionCode_;
    /**
     * <code>optional string regionCode = 4;</code>
     */
    public boolean hasRegionCode() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string regionCode = 4;</code>
     */
    public java.lang.String getRegionCode() {
      java.lang.Object ref = regionCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          regionCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string regionCode = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRegionCodeBytes() {
      java.lang.Object ref = regionCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        regionCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REGIONNAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object regionName_;
    /**
     * <code>optional string regionName = 5;</code>
     */
    public boolean hasRegionName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string regionName = 5;</code>
     */
    public java.lang.String getRegionName() {
      java.lang.Object ref = regionName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          regionName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string regionName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRegionNameBytes() {
      java.lang.Object ref = regionName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        regionName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 6;
    private volatile java.lang.Object city_;
    /**
     * <code>optional string city = 6;</code>
     */
    public boolean hasCity() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string city = 6;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          city_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string city = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ZIPCODE_FIELD_NUMBER = 7;
    private volatile java.lang.Object zipCode_;
    /**
     * <code>optional string zipCode = 7;</code>
     */
    public boolean hasZipCode() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string zipCode = 7;</code>
     */
    public java.lang.String getZipCode() {
      java.lang.Object ref = zipCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          zipCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string zipCode = 7;</code>
     */
    public com.google.protobuf.ByteString
        getZipCodeBytes() {
      java.lang.Object ref = zipCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zipCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMEZONE_FIELD_NUMBER = 8;
    private volatile java.lang.Object timeZone_;
    /**
     * <code>optional string timeZone = 8;</code>
     */
    public boolean hasTimeZone() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string timeZone = 8;</code>
     */
    public java.lang.String getTimeZone() {
      java.lang.Object ref = timeZone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timeZone_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string timeZone = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTimeZoneBytes() {
      java.lang.Object ref = timeZone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeZone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LATITUDE_FIELD_NUMBER = 9;
    private volatile java.lang.Object latitude_;
    /**
     * <code>optional string latitude = 9;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string latitude = 9;</code>
     */
    public java.lang.String getLatitude() {
      java.lang.Object ref = latitude_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          latitude_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string latitude = 9;</code>
     */
    public com.google.protobuf.ByteString
        getLatitudeBytes() {
      java.lang.Object ref = latitude_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        latitude_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LONGITUDE_FIELD_NUMBER = 10;
    private volatile java.lang.Object longitude_;
    /**
     * <code>optional string longitude = 10;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string longitude = 10;</code>
     */
    public java.lang.String getLongitude() {
      java.lang.Object ref = longitude_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          longitude_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string longitude = 10;</code>
     */
    public com.google.protobuf.ByteString
        getLongitudeBytes() {
      java.lang.Object ref = longitude_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        longitude_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METROCODE_FIELD_NUMBER = 11;
    private volatile java.lang.Object metroCode_;
    /**
     * <code>optional string metroCode = 11;</code>
     */
    public boolean hasMetroCode() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string metroCode = 11;</code>
     */
    public java.lang.String getMetroCode() {
      java.lang.Object ref = metroCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          metroCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string metroCode = 11;</code>
     */
    public com.google.protobuf.ByteString
        getMetroCodeBytes() {
      java.lang.Object ref = metroCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metroCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ip_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, countryCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, countryName_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, regionCode_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, regionName_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, city_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, zipCode_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, timeZone_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, latitude_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, longitude_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, metroCode_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ip_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, countryCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, countryName_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, regionCode_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, regionName_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, city_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, zipCode_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, timeZone_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, latitude_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, longitude_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, metroCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ResponseProtos.Response)) {
        return super.equals(obj);
      }
      ResponseProtos.Response other = (ResponseProtos.Response) obj;

      boolean result = true;
      result = result && (hasIp() == other.hasIp());
      if (hasIp()) {
        result = result && getIp()
            .equals(other.getIp());
      }
      result = result && (hasCountryCode() == other.hasCountryCode());
      if (hasCountryCode()) {
        result = result && getCountryCode()
            .equals(other.getCountryCode());
      }
      result = result && (hasCountryName() == other.hasCountryName());
      if (hasCountryName()) {
        result = result && getCountryName()
            .equals(other.getCountryName());
      }
      result = result && (hasRegionCode() == other.hasRegionCode());
      if (hasRegionCode()) {
        result = result && getRegionCode()
            .equals(other.getRegionCode());
      }
      result = result && (hasRegionName() == other.hasRegionName());
      if (hasRegionName()) {
        result = result && getRegionName()
            .equals(other.getRegionName());
      }
      result = result && (hasCity() == other.hasCity());
      if (hasCity()) {
        result = result && getCity()
            .equals(other.getCity());
      }
      result = result && (hasZipCode() == other.hasZipCode());
      if (hasZipCode()) {
        result = result && getZipCode()
            .equals(other.getZipCode());
      }
      result = result && (hasTimeZone() == other.hasTimeZone());
      if (hasTimeZone()) {
        result = result && getTimeZone()
            .equals(other.getTimeZone());
      }
      result = result && (hasLatitude() == other.hasLatitude());
      if (hasLatitude()) {
        result = result && getLatitude()
            .equals(other.getLatitude());
      }
      result = result && (hasLongitude() == other.hasLongitude());
      if (hasLongitude()) {
        result = result && getLongitude()
            .equals(other.getLongitude());
      }
      result = result && (hasMetroCode() == other.hasMetroCode());
      if (hasMetroCode()) {
        result = result && getMetroCode()
            .equals(other.getMetroCode());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIp()) {
        hash = (37 * hash) + IP_FIELD_NUMBER;
        hash = (53 * hash) + getIp().hashCode();
      }
      if (hasCountryCode()) {
        hash = (37 * hash) + COUNTRYCODE_FIELD_NUMBER;
        hash = (53 * hash) + getCountryCode().hashCode();
      }
      if (hasCountryName()) {
        hash = (37 * hash) + COUNTRYNAME_FIELD_NUMBER;
        hash = (53 * hash) + getCountryName().hashCode();
      }
      if (hasRegionCode()) {
        hash = (37 * hash) + REGIONCODE_FIELD_NUMBER;
        hash = (53 * hash) + getRegionCode().hashCode();
      }
      if (hasRegionName()) {
        hash = (37 * hash) + REGIONNAME_FIELD_NUMBER;
        hash = (53 * hash) + getRegionName().hashCode();
      }
      if (hasCity()) {
        hash = (37 * hash) + CITY_FIELD_NUMBER;
        hash = (53 * hash) + getCity().hashCode();
      }
      if (hasZipCode()) {
        hash = (37 * hash) + ZIPCODE_FIELD_NUMBER;
        hash = (53 * hash) + getZipCode().hashCode();
      }
      if (hasTimeZone()) {
        hash = (37 * hash) + TIMEZONE_FIELD_NUMBER;
        hash = (53 * hash) + getTimeZone().hashCode();
      }
      if (hasLatitude()) {
        hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + getLatitude().hashCode();
      }
      if (hasLongitude()) {
        hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + getLongitude().hashCode();
      }
      if (hasMetroCode()) {
        hash = (37 * hash) + METROCODE_FIELD_NUMBER;
        hash = (53 * hash) + getMetroCode().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ResponseProtos.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseProtos.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseProtos.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseProtos.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseProtos.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseProtos.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseProtos.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ResponseProtos.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResponseProtos.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ResponseProtos.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResponseProtos.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ResponseProtos.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ResponseProtos.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code retrofit2ee.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:retrofit2ee.Response)
        ResponseProtos.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ResponseProtos.internal_static_retrofit2ee_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ResponseProtos.internal_static_retrofit2ee_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ResponseProtos.Response.class, ResponseProtos.Response.Builder.class);
      }

      // Construct using org.djr.retrofit2ee.protobuf.ResponseProtos.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        countryCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        countryName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        regionCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        regionName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        city_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        zipCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        timeZone_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        latitude_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        longitude_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        metroCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ResponseProtos.internal_static_retrofit2ee_Response_descriptor;
      }

      public ResponseProtos.Response getDefaultInstanceForType() {
        return ResponseProtos.Response.getDefaultInstance();
      }

      public ResponseProtos.Response build() {
        ResponseProtos.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ResponseProtos.Response buildPartial() {
        ResponseProtos.Response result = new ResponseProtos.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.countryCode_ = countryCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.countryName_ = countryName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.regionCode_ = regionCode_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.regionName_ = regionName_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.city_ = city_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.zipCode_ = zipCode_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.timeZone_ = timeZone_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.metroCode_ = metroCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ResponseProtos.Response) {
          return mergeFrom((ResponseProtos.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ResponseProtos.Response other) {
        if (other == ResponseProtos.Response.getDefaultInstance()) return this;
        if (other.hasIp()) {
          bitField0_ |= 0x00000001;
          ip_ = other.ip_;
          onChanged();
        }
        if (other.hasCountryCode()) {
          bitField0_ |= 0x00000002;
          countryCode_ = other.countryCode_;
          onChanged();
        }
        if (other.hasCountryName()) {
          bitField0_ |= 0x00000004;
          countryName_ = other.countryName_;
          onChanged();
        }
        if (other.hasRegionCode()) {
          bitField0_ |= 0x00000008;
          regionCode_ = other.regionCode_;
          onChanged();
        }
        if (other.hasRegionName()) {
          bitField0_ |= 0x00000010;
          regionName_ = other.regionName_;
          onChanged();
        }
        if (other.hasCity()) {
          bitField0_ |= 0x00000020;
          city_ = other.city_;
          onChanged();
        }
        if (other.hasZipCode()) {
          bitField0_ |= 0x00000040;
          zipCode_ = other.zipCode_;
          onChanged();
        }
        if (other.hasTimeZone()) {
          bitField0_ |= 0x00000080;
          timeZone_ = other.timeZone_;
          onChanged();
        }
        if (other.hasLatitude()) {
          bitField0_ |= 0x00000100;
          latitude_ = other.latitude_;
          onChanged();
        }
        if (other.hasLongitude()) {
          bitField0_ |= 0x00000200;
          longitude_ = other.longitude_;
          onChanged();
        }
        if (other.hasMetroCode()) {
          bitField0_ |= 0x00000400;
          metroCode_ = other.metroCode_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ResponseProtos.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ResponseProtos.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object ip_ = "";
      /**
       * <code>optional string ip = 1;</code>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ip_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ip_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object countryCode_ = "";
      /**
       * <code>optional string countryCode = 2;</code>
       */
      public boolean hasCountryCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string countryCode = 2;</code>
       */
      public java.lang.String getCountryCode() {
        java.lang.Object ref = countryCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            countryCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string countryCode = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCountryCodeBytes() {
        java.lang.Object ref = countryCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          countryCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string countryCode = 2;</code>
       */
      public Builder setCountryCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        countryCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string countryCode = 2;</code>
       */
      public Builder clearCountryCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        countryCode_ = getDefaultInstance().getCountryCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string countryCode = 2;</code>
       */
      public Builder setCountryCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        countryCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object countryName_ = "";
      /**
       * <code>optional string countryName = 3;</code>
       */
      public boolean hasCountryName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string countryName = 3;</code>
       */
      public java.lang.String getCountryName() {
        java.lang.Object ref = countryName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            countryName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string countryName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCountryNameBytes() {
        java.lang.Object ref = countryName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          countryName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string countryName = 3;</code>
       */
      public Builder setCountryName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        countryName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string countryName = 3;</code>
       */
      public Builder clearCountryName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        countryName_ = getDefaultInstance().getCountryName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string countryName = 3;</code>
       */
      public Builder setCountryNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        countryName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object regionCode_ = "";
      /**
       * <code>optional string regionCode = 4;</code>
       */
      public boolean hasRegionCode() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string regionCode = 4;</code>
       */
      public java.lang.String getRegionCode() {
        java.lang.Object ref = regionCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            regionCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string regionCode = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRegionCodeBytes() {
        java.lang.Object ref = regionCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          regionCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string regionCode = 4;</code>
       */
      public Builder setRegionCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        regionCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string regionCode = 4;</code>
       */
      public Builder clearRegionCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        regionCode_ = getDefaultInstance().getRegionCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string regionCode = 4;</code>
       */
      public Builder setRegionCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        regionCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object regionName_ = "";
      /**
       * <code>optional string regionName = 5;</code>
       */
      public boolean hasRegionName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string regionName = 5;</code>
       */
      public java.lang.String getRegionName() {
        java.lang.Object ref = regionName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            regionName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string regionName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getRegionNameBytes() {
        java.lang.Object ref = regionName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          regionName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string regionName = 5;</code>
       */
      public Builder setRegionName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        regionName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string regionName = 5;</code>
       */
      public Builder clearRegionName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        regionName_ = getDefaultInstance().getRegionName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string regionName = 5;</code>
       */
      public Builder setRegionNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        regionName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>optional string city = 6;</code>
       */
      public boolean hasCity() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string city = 6;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            city_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string city = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string city = 6;</code>
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string city = 6;</code>
       */
      public Builder clearCity() {
        bitField0_ = (bitField0_ & ~0x00000020);
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>optional string city = 6;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        city_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object zipCode_ = "";
      /**
       * <code>optional string zipCode = 7;</code>
       */
      public boolean hasZipCode() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string zipCode = 7;</code>
       */
      public java.lang.String getZipCode() {
        java.lang.Object ref = zipCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            zipCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string zipCode = 7;</code>
       */
      public com.google.protobuf.ByteString
          getZipCodeBytes() {
        java.lang.Object ref = zipCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          zipCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string zipCode = 7;</code>
       */
      public Builder setZipCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        zipCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string zipCode = 7;</code>
       */
      public Builder clearZipCode() {
        bitField0_ = (bitField0_ & ~0x00000040);
        zipCode_ = getDefaultInstance().getZipCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string zipCode = 7;</code>
       */
      public Builder setZipCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        zipCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object timeZone_ = "";
      /**
       * <code>optional string timeZone = 8;</code>
       */
      public boolean hasTimeZone() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string timeZone = 8;</code>
       */
      public java.lang.String getTimeZone() {
        java.lang.Object ref = timeZone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            timeZone_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string timeZone = 8;</code>
       */
      public com.google.protobuf.ByteString
          getTimeZoneBytes() {
        java.lang.Object ref = timeZone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timeZone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string timeZone = 8;</code>
       */
      public Builder setTimeZone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        timeZone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string timeZone = 8;</code>
       */
      public Builder clearTimeZone() {
        bitField0_ = (bitField0_ & ~0x00000080);
        timeZone_ = getDefaultInstance().getTimeZone();
        onChanged();
        return this;
      }
      /**
       * <code>optional string timeZone = 8;</code>
       */
      public Builder setTimeZoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        timeZone_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object latitude_ = "";
      /**
       * <code>optional string latitude = 9;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string latitude = 9;</code>
       */
      public java.lang.String getLatitude() {
        java.lang.Object ref = latitude_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            latitude_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string latitude = 9;</code>
       */
      public com.google.protobuf.ByteString
          getLatitudeBytes() {
        java.lang.Object ref = latitude_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          latitude_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string latitude = 9;</code>
       */
      public Builder setLatitude(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string latitude = 9;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000100);
        latitude_ = getDefaultInstance().getLatitude();
        onChanged();
        return this;
      }
      /**
       * <code>optional string latitude = 9;</code>
       */
      public Builder setLatitudeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        latitude_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object longitude_ = "";
      /**
       * <code>optional string longitude = 10;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string longitude = 10;</code>
       */
      public java.lang.String getLongitude() {
        java.lang.Object ref = longitude_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            longitude_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string longitude = 10;</code>
       */
      public com.google.protobuf.ByteString
          getLongitudeBytes() {
        java.lang.Object ref = longitude_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          longitude_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string longitude = 10;</code>
       */
      public Builder setLongitude(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string longitude = 10;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000200);
        longitude_ = getDefaultInstance().getLongitude();
        onChanged();
        return this;
      }
      /**
       * <code>optional string longitude = 10;</code>
       */
      public Builder setLongitudeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        longitude_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object metroCode_ = "";
      /**
       * <code>optional string metroCode = 11;</code>
       */
      public boolean hasMetroCode() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string metroCode = 11;</code>
       */
      public java.lang.String getMetroCode() {
        java.lang.Object ref = metroCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            metroCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string metroCode = 11;</code>
       */
      public com.google.protobuf.ByteString
          getMetroCodeBytes() {
        java.lang.Object ref = metroCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          metroCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string metroCode = 11;</code>
       */
      public Builder setMetroCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        metroCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string metroCode = 11;</code>
       */
      public Builder clearMetroCode() {
        bitField0_ = (bitField0_ & ~0x00000400);
        metroCode_ = getDefaultInstance().getMetroCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string metroCode = 11;</code>
       */
      public Builder setMetroCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        metroCode_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:retrofit2ee.Response)
    }

    // @@protoc_insertion_point(class_scope:retrofit2ee.Response)
    private static final ResponseProtos.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ResponseProtos.Response();
    }

    public static ResponseProtos.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public ResponseProtos.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_retrofit2ee_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_retrofit2ee_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Response.proto\022\013retrofit2ee\"\321\001\n\010Respon" +
      "se\022\n\n\002ip\030\001 \001(\t\022\023\n\013countryCode\030\002 \001(\t\022\023\n\013c" +
      "ountryName\030\003 \001(\t\022\022\n\nregionCode\030\004 \001(\t\022\022\n\n" +
      "regionName\030\005 \001(\t\022\014\n\004city\030\006 \001(\t\022\017\n\007zipCod" +
      "e\030\007 \001(\t\022\020\n\010timeZone\030\010 \001(\t\022\020\n\010latitude\030\t " +
      "\001(\t\022\021\n\tlongitude\030\n \001(\t\022\021\n\tmetroCode\030\013 \001(" +
      "\tB%\n\023org.djr.retrofit2eeB\016ResponseProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_retrofit2ee_Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_retrofit2ee_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_retrofit2ee_Response_descriptor,
        new java.lang.String[] { "Ip", "CountryCode", "CountryName", "RegionCode", "RegionName", "City", "ZipCode", "TimeZone", "Latitude", "Longitude", "MetroCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
